import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      //label: '介绍',
      id: 'intro',
    },
    {
      type: 'category',
      label: '入门',
      link: {
        type: 'generated-index',
        slug: '/getting-started',
      },
      items: [
        'beginner/quick-start',
        'beginner/multi-assemblies-to-obfuscate',
        'beginner/configuration',
        'beginner/dynamic-secret-key',
        'beginner/work-with-hybridclr',
      ],
    },
    {
      type: 'category',
      label: '手册',
      link: {
        type: 'generated-index',
        slug: '/manual',
      },
      items: [
        'manual/installation',
        'manual/configuration',
        'manual/menu',
        'manual/assembly',
        'manual/encryption',
        'manual/method-body-obfuscation',
        'manual/obfuscation-pass',
        'manual/customattributes',
        'manual/symbol-obfuscation',
        'manual/const-encryption',
        'manual/field-encryption',
        'manual/call-obfuscation',
        'manual/build-pipeline',
        'manual/run-obfuscation-standalonely',
        'manual/incremental-obfuscation-and-hotupdate',
        'manual/work-with-hybridclr',
        'manual/serialization-reflection',
        'manual/deobfuscate-stacktrace',
      ],
    },
    {
      type: 'category',
      label: '帮助',
      link: {
        type: 'generated-index',
        slug: '/help',
      },
      items: [
        'help/faq',
      ],
    },
  ],

};

export default sidebars;
